### ISSUE TITLE
post general information to #rules-and-info in Discord

### ISSUE THREAD

**Issue by autoboxer** [dome-candy/domebot#5]
### tasks

- [ ] create banners for the different information sections
- [ ] post rules
- [ ] post channels guide
- [ ] post roles guide
- [ ] post other useful information

### definition of done

- all necessary information is posted to #rules-and-info under the appropriate banners
