### ISSUE TITLE
merge all code into the github codebase and get it working

### ISSUE THREAD

**Issue by autoboxer** [dome-candy/domebot#6]
### tasks

- [ ] fix prompts
- [ ] add create raid functionality
- [ ] add join raid functionality
- [ ] add leave raid functionality
- [ ] add find raid functionality

### definition of done

- all code from @Astradari is integrated into the github repo
- the bot code functions as expected for all actions

**Comment by Astradari** [comment]
Integration started, create event process semi-functional.
